language: go
go_import_path: "github.com/go-macaroon-bakery/macaroon-bakery/v3"
go: 
  - "1.12.x"
script: GO111MODULE=on go test ./...
services:
  - mongodb
  - postgresql
addons:
  postgresql: "9.5"
